import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { type Page } from '@playwright/test';
import { expect, openNewProject, test } from './fixtures';

async function submitDeploymentKey(page: Page) {
  let key = readFileSync(resolve('../runtime/secrets/access_key'), 'utf8').trim();
  try { await page.getByLabel('全局访问密钥').fill(key); }
  catch { throw new Error('无法填写登录字段；为保护密钥，已隐藏调用参数。'); }
  finally { key = ''; }
  await page.getByRole('button', { name: '登录', exact: true }).click();
}

async function runControl(page: Page, action: string, buttonName: string, actionLabel: string) {
  const path = `/api/v1${new URL(page.url()).pathname}/${action}`;
  let button = page.getByRole('button', { name: buttonName, exact: true });
  for (let attempt = 0; attempt < 3; attempt += 1) {
    const answer = page.waitForResponse(response =>
      new URL(response.url()).pathname === path && response.request().method() === 'POST',
    { timeout: 5000 });
    await button.click();
    const response = await answer;
    if (response.status() !== 409) {
      expect(response.status(), `操作 ${action} 返回成功`).toBe(200);
      return;
    }
    expect((await response.json()).reason_code).toBe('version_conflict');
    const conflict = page.getByTestId('version-conflict');
    await expect(conflict).toBeVisible();
    // Simulate the operator's explicit confirmation of the newly displayed version.
    button = conflict.getByRole('button', { name: new RegExp(`按新状态确认${actionLabel}`) });
  }
  throw new Error(`操作 ${action} 的状态持续变化，未取得成功响应。`);
}

async function awaitAutomaticEnd(page: Page) {
  const path = `/api/v1${new URL(page.url()).pathname}`;
  const deadline = Date.now() + 15000;
  while (Date.now() < deadline) {
    const response = await page.request.get(path, { timeout: Math.max(1, Math.min(5000, deadline - Date.now())) });
    expect(response.status()).toBe(200);
    const run = await response.json();
    if (run.status === 'waiting' && run.phase === 'awaiting_human') return;
    if (['failed', 'cancelled', 'closed'].includes(run.status)) {
      throw new Error(`假 Run 提前结束：${run.status} / ${run.reason_code || '无原因码'}。`);
    }
    await page.waitForTimeout(100);
  }
  throw new Error('后端假 Run 在 15 秒内未结束自动阶段。');
}

// Business checks use independent API sessions. These checks start anonymous and exercise the
// real key-submission interface instead.
test.describe('the entry point', () => {
  test.use({ authenticated: false });

  test('anonymous deep links and bundles are protected; submitting the key creates an HttpOnly session', async ({ page, request }) => {
    expect((await request.get('/api/v1/runs')).status()).toBe(401);
    expect((await request.get('/assets/index.js')).status()).toBe(401);
    await page.goto('/runs/00000000-0000-0000-0000-000000000000');
    await expect(page).toHaveURL(/\/login$/);
    await expect(page).toHaveTitle('登录 · HuntWeave');
    await submitDeploymentKey(page);
    await expect(page.getByRole('heading', { name: '先确定范围，再开始研究。' })).toBeVisible();
    await expect(page).toHaveTitle('HuntWeave · 开发演示');
    await expect(page.getByText('界巡', { exact: false })).toHaveCount(0);
    const cookies = await page.context().cookies();
    const cookie = cookies.find(item => item.name === 'huntweave_local_session');
    expect(cookie?.httpOnly).toBe(true);
    expect(cookie?.sameSite).toBe('Strict');
    expect(await page.evaluate(() => [localStorage.length, sessionStorage.length])).toEqual([0, 0]);
    await page.getByRole('button', { name: '退出登录' }).click();
    await expect(page).toHaveURL(/\/login$/);
    expect((await page.request.get('/api/v1/runs')).status()).toBe(401);
  });

  test('a wrong key is refused on its own merits and a right one is accepted again', async ({ page }) => {
    // Submitting the key is not rate limited: the key is generated by the deployment rather than
    // chosen by a person, so repeating the request is not what a per-address counter would prevent —
    // and such a counter would lock the operator out of their own platform.
    await page.goto('/login');
    for (let attempt = 0; attempt < 6; attempt += 1) {
      await page.getByLabel('全局访问密钥').fill(`wrong-key-${attempt}-${'x'.repeat(32)}`);
      await page.getByRole('button', { name: '登录', exact: true }).click();
      await expect(page.getByRole('alert')).toContainText('密钥不正确');
    }
    await submitDeploymentKey(page);
    await expect(page.getByRole('heading', { name: '先确定范围，再开始研究。' })).toBeVisible();
  });
});

test('preview, freeze, idempotent draft creation, queue, reload and logout', async ({ page }) => {
  const projectName = `假执行验证 ${Date.now()} <script>window.huntweaveInjected=true</script>`;
  await openNewProject(page);
  await page.getByLabel('项目名称', { exact: true }).fill(projectName);
  await page.getByRole('button', { name: '创建项目', exact: true }).click();
  await expect(page.getByLabel('所属项目')).not.toHaveValue('');
  await page.getByLabel(/目标 IP/).fill('192.0.2.10\nhttps://example.com\n2001:db8::1');
  await page.getByRole('button', { name: '预览 IP', exact: true }).click();
  await expect(page.getByText('存在错误，不能提交', { exact: false })).toBeVisible();
  await expect(page.getByText('当前部署未启用 IPv6 隔离，不能运行。')).toBeVisible();
  await expect(page.getByRole('button', { name: '保存授权快照' })).toBeDisabled();
  await page.getByLabel(/目标 IP/).fill('192.0.2.10\n192.0.2.10\n198.51.100.20');
  await page.getByRole('button', { name: '预览 IP', exact: true }).click();
  await expect(page.getByText('与第 1 行重复，已合并')).toBeVisible();
  await page.getByLabel('TCP 端口范围').selectOption('custom-tcp-v1');
  await page.getByLabel('端口与范围').fill('443,80,8000-8002,80');
  await page.getByRole('button', { name: '展开端口' }).click();
  await expect(page.getByText('5 个明确授权端口')).toBeVisible();
  await page.getByLabel('授权说明', { exact: true }).fill('只用于本地假执行验证');
  await page.getByRole('button', { name: '保存授权快照' }).click();
  await page.getByRole('button', { name: '创建假 Run' }).click();
  await expect(page).toHaveURL(/\/runs\/[a-f0-9-]+$/);
  const firstRunUrl = page.url();
  const firstCount = (await (await page.request.get('/api/v1/runs')).json()).length;
  await page.getByRole('button', { name: '创建假 Run' }).click();
  await expect(page.getByRole('button', { name: '退出登录' })).toBeEnabled();
  await expect(page).toHaveURL(firstRunUrl);
  expect((await (await page.request.get('/api/v1/runs')).json()).length).toBe(firstCount);
  // A new immutable scope needs a new key, even if its input fields are unchanged.
  await page.getByRole('button', { name: '保存授权快照' }).click();
  await page.getByRole('button', { name: '创建假 Run' }).click();
  await expect(page).not.toHaveURL(firstRunUrl);
  expect((await (await page.request.get('/api/v1/runs')).json()).length).toBe(firstCount + 1);
  const runUrl = page.url();
  await expect(page.getByRole('button', { name: '将假 Run 加入队列' })).toBeVisible();
  await page.getByRole('button', { name: '将假 Run 加入队列' }).click();
  await expect(page.getByRole('button', { name: '将假 Run 加入队列' })).toHaveCount(0);
  await page.reload();
  await expect(page).toHaveURL(runUrl);
  await expect(page.getByRole('region', { name: '玻璃鱼缸执行台' })).toBeVisible();
  await awaitAutomaticEnd(page);
  await expect(page.getByRole('region', { name: 'Run 详情' }).getByText('自动阶段结束 · 待人工复审', { exact: true })).toBeVisible();
  await expect(page.getByText('只用于本地假执行验证', { exact: true })).toBeVisible();
  expect(await page.evaluate(() => Reflect.get(window, 'huntweaveInjected'))).toBeUndefined();
  await page.screenshot({ path: '../runtime/validation/p0-b-workspace.png', fullPage: true });
  await page.getByRole('button', { name: '退出登录' }).click();
  await expect(page).toHaveURL(/\/login$/);
});

async function createDemo(page: Page, scenario: string, start = true) {
  await openNewProject(page);
  await page.getByLabel('项目名称', { exact: true }).fill(`P0 控制 ${scenario} ${Date.now()}`);
  await page.getByRole('button', { name: '创建项目', exact: true }).click();
  await page.getByLabel(/目标 IP/).fill('192.0.2.30');
  await page.getByRole('button', { name: '预览 IP', exact: true }).click();
  await page.getByLabel('TCP 端口范围').selectOption('custom-tcp-v1');
  await page.getByLabel('端口与范围').fill('80');
  await page.getByRole('button', { name: '展开端口' }).click();
  await page.getByLabel('授权说明', { exact: true }).fill('固定假动作浏览器验收，无目标连接');
  await page.getByRole('button', { name: '保存授权快照' }).click();
  await page.getByLabel('假输出场景').selectOption(scenario);
  await page.getByRole('button', { name: '创建假 Run' }).click();
  await expect(page).toHaveURL(/\/runs\/[a-f0-9-]+$/);
  if (start) await page.getByRole('button', { name: '将假 Run 加入队列' }).click();
}

test('pause, reload, resume preview, original evidence and human close preserve a Run', async ({ page }) => {
  await createDemo(page, 'positive');
  const originalUrl = page.url();
  await runControl(page, 'pause', '暂停 Run', '暂停');
  await expect(page.getByRole('button', { name: '查看恢复预览' })).toBeVisible();
  await page.reload();
  await expect(page).toHaveURL(originalUrl);
  await page.getByRole('button', { name: '查看恢复预览' }).click();
  await expect(page.getByRole('region', { name: '恢复预览' })).toBeVisible();
  await expect(page.getByRole('button', { name: '按预览恢复' })).toBeEnabled();
  await runControl(page, 'resume', '按预览恢复', '恢复');
  await awaitAutomaticEnd(page);
  await expect(page.getByRole('button', { name: '结束演示', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '查看原始证据' }).first().click();
  await expect(page.getByRole('region', { name: '原始证据' })).toBeVisible();
  const evidence = page.getByRole('region', { name: '原始证据' });
  await expect(evidence.locator('pre')).not.toBeEmpty();
  await expect(evidence).toContainText('SHA-256');
  await runControl(page, 'close', '结束演示', '结束演示');
  await expect(page.getByRole('region', { name: 'Run 详情' }).getByText('演示已结束', { exact: true })).toBeVisible();
  await page.reload();
  await expect(page).toHaveURL(originalUrl);
  await expect(page.getByRole('region', { name: 'Run 详情' }).getByText('演示已结束', { exact: true })).toBeVisible();
  await page.screenshot({ path: '../runtime/validation/p0-console.png', fullPage: true });
});

test('the console records an operator verdict on an unknown call and shows what is missing', async ({ page }) => {
  // deploy/verify_p0.py leaves one Run with an unconfirmed call and prints its id; the
  // browser check rules on it the way an operator would.
  const runId = process.env.HUNTWEAVE_E2E_RECONCILE_RUN_ID;
  test.skip(!runId, 'Set HUNTWEAVE_E2E_RECONCILE_RUN_ID from the reconciliation probe.');
  await page.goto(`/runs/${runId}`);
  const region = page.getByRole('region', { name: '待核对调用' });
  await expect(region).toBeVisible();
  // Execution facts and the missing conditions are shown before any verdict is offered.
  await expect(region).toContainText('执行端事实');
  await expect(region).toContainText('停止确认 未确认');
  await expect(region).toContainText('结果未裁定');
  await expect(region).toContainText('仍缺条件');
  // A verdict the execution ledger contradicts is refused, not silently accepted.
  await region.getByRole('button', { name: '确认未执行' }).click();
  await expect(page.getByRole('alert').filter({ hasText: '执行端记录与该裁定矛盾' })).toBeVisible();
  // What is recorded is the operator's own evidence-bound decision.
  await region.getByLabel('裁定说明').fill('结果未到达；执行端账本证明动作已经开始');
  await region.getByRole('button', { name: '确认已执行' }).click();
  await expect(region).toContainText('操作员裁定：确认已执行');
  await expect(region).toContainText('结果未到达；执行端账本证明动作已经开始');
  await expect(region).toContainText('允许重派 否');
  // A recorded verdict is a decision, not a form: it gives way to the record itself, and a
  // conflicting verdict is refused by the interface rather than rewriting it in place.
  await expect(region.getByRole('button', { name: '确认未执行' })).toHaveCount(0);
  // No result was invented for the call, and the stop is still the execution side's to give.
  await expect(region).toContainText('停止未确认');
  await page.screenshot({ path: '../runtime/validation/p1-reconciliation.png', fullPage: true });
});

test('cancel waits for Runner acknowledgement and prevents later dispatch', async ({ page }) => {
  await createDemo(page, 'negative');
  // Wait for the console to show the first dispatched call, so the cancel exercises the
  // acknowledgement path against a live snapshot instead of racing an empty console.
  await expect(page.getByText('fake.collect', { exact: false }).first()).toBeVisible();
  await runControl(page, 'cancel', '取消 Run', '取消');
  await expect(page.getByRole('region', { name: 'Run 详情' }).getByText('已取消', { exact: true })).toBeVisible();
  const snapshotUrl = `/api/v1${new URL(page.url()).pathname}/snapshot`;
  const first = await (await page.request.get(snapshotUrl)).json();
  await page.reload();
  await expect(page.getByRole('region', { name: 'Run 详情' }).getByText('已取消', { exact: true })).toBeVisible();
  const second = await (await page.request.get(snapshotUrl)).json();
  expect(second.calls.length).toBe(first.calls.length);
  expect(second.budget).toEqual(first.budget);
  await expect(page.getByRole('button', { name: '按预览恢复' })).toHaveCount(0);
});

test('the console reports the execution mode and readiness from the capability answer', async ({ page }) => {
  const capability = await (await page.request.get('/api/v1/system/capabilities')).json();
  expect(capability.real_execution_ready).toBe(false);
  expect(capability.mode).toBe('demonstration');
  expect(capability.reason_code).toBe('environment_unsupported');
  const readiness = page.getByTestId('execution-readiness');
  await expect(readiness).toContainText('当前执行模式：开发演示 / 假执行');
  // The reason on the page is this deployment's own blocking condition, not another copy of it.
  await expect(readiness).toContainText('当前宿主环境未通过真实执行的隔离与 profile 验收。');
  await expect(page.locator('header .badge')).toHaveText('开发演示 / 假执行');
  // Every ADR-0010 gate the answer carries is rendered, with as many unmet as the answer has.
  const gates = page.getByTestId('execution-gates').locator('li');
  const unmet = capability.gates.filter((gate: { ready: boolean }) => !gate.ready);
  await expect(gates).toHaveCount(capability.gates.length);
  await expect(gates.filter({ hasText: '已满足' })).toHaveCount(capability.gates.length - unmet.length);
  await page.screenshot({ path: '../runtime/validation/p1-capability-honesty.png', fullPage: true });
});

test('a capability answer that is not ready is never rendered as ready', async ({ page }) => {
  await createDemo(page, 'positive');
  // The execution side is unreachable: the platform must show the gap and no ready state.
  await page.route('**/api/v1/system/capabilities', (route) => route.fulfill({
    status: 200, contentType: 'application/json',
    body: JSON.stringify({
      protocol_version: '1', mode: 'demonstration', execution_profile: 'fake-p0-v1',
      fake_execution_ready: false, real_execution_ready: false,
      reason_code: 'runner_unavailable', observed_at: null, gates: [],
    }),
  }));
  await page.reload();
  const readiness = page.getByTestId('execution-readiness');
  await expect(readiness).toContainText('执行端不可达，无法确认当前执行力。');
  await expect(readiness).toContainText('真实执行未开放');
  await expect(readiness).toContainText('执行端不可用：固定假动作链路当前无法推进。');
  await expect(page.locator('header .badge')).toHaveText('开发演示 / 假执行');
  await expect(page.getByTestId('execution-gates').locator('li')).toHaveCount(0);
  await expect(page.getByTestId('console-execution-mode')).toContainText('真实执行未开放');
  await expect(page.getByTestId('execution-unavailable')).toBeVisible();
  await page.screenshot({ path: '../runtime/validation/p1-capability-unavailable.png', fullPage: true });
});

test('a version conflict is shown and re-sent only when the operator confirms', async ({ page }) => {
  await createDemo(page, 'positive', false);
  const snapshotPath = `/api/v1${new URL(page.url()).pathname}/snapshot`;
  // Freeze the state the console renders, so the operator keeps looking at the version they were
  // shown while the scheduler really advances the Run behind them.
  const start = await (await page.request.get(snapshotPath)).json();
  const frozen = JSON.stringify(start);
  await page.route('**/api/v1/runs/*/snapshot', (route) => route.fulfill({ status: 200, contentType: 'application/json', body: frozen }));
  // Another operator starts through the real API while this page keeps its displayed draft.
  // This creates the conflict deterministically without waiting for scheduler timing.
  const session = await (await page.request.get('/auth/session')).json();
  const changed = await page.request.post(`/api/v1${new URL(page.url()).pathname}/start`, {
    data: { version: start.run.version },
    headers: { Origin: new URL(page.url()).origin, 'X-CSRF-Token': session.csrf_token },
    timeout: 5000,
  });
  expect(changed.status()).toBe(200);
  expect((await changed.json()).version).toBeGreaterThan(start.run.version);
  let attempts = 0;
  await page.route('**/api/v1/runs/*/cancel', async (route) => {
    attempts += 1;
    if (attempts === 1) {
      // The first decision is the one built from the state the operator saw; the server refuses
      // it, and the console stops being frozen so the panel can show what is current now.
      await page.unroute('**/api/v1/runs/*/snapshot');
    }
    await route.continue();
  });
  await page.getByRole('button', { name: '取消 Run', exact: true }).click();
  const conflict = page.getByTestId('version-conflict');
  await expect(conflict).toBeVisible();
  await expect(conflict).toContainText('状态已变化，操作未执行');
  await expect(conflict).toContainText('不会替你重发这次取消');
  // Nothing was re-sent from the state the operator never saw.
  expect(attempts).toBe(1);
  const panel = await conflict.innerText();
  const seen = Number(/你点击时的状态版本是 (\d+)/.exec(panel)?.[1]);
  const now = Number(/（版本 (\d+)）/.exec(panel)?.[1]);
  expect(now).toBeGreaterThan(seen);
  await page.screenshot({ path: '../runtime/validation/p1-version-conflict.png', fullPage: true });
  // Only the operator's confirmation sends it again, and it carries the version on screen.
  for (let round = 0; round < 4 && await conflict.isVisible(); round += 1) {
    await conflict.getByRole('button', { name: /按新状态确认取消/ }).click();
    await page.waitForTimeout(300);
  }
  expect(attempts).toBeGreaterThanOrEqual(2);
  await expect(page.getByRole('region', { name: 'Run 详情' }).getByText('已取消', { exact: true })).toBeVisible();
});
